# List of topics to record when running the all-sensors bringup.
# Update this file to add/remove topics; the launch file loads it automatically.

record:
      enabled: false
      bag_name: test_run
      output_dir: temp/bags

topics:
      - /navi_lidar/points
      - /galaxy_camera/image_raw
      - /galaxy_camera/camera_info
      - /galaxy_camera/image_raw/compressed
      - /imu/data
      - /imu/mag
      - /imu/nav_sat_fix
      - /imu/pos_ecef
      - /imu/pres
      - /imu/temp
      - /imu/utc_ref
      - /imu/velocity
      - /sbg/air_data
      - /sbg/ekf_euler
      - /sbg/ekf_nav
      - /sbg/ekf_quat
      - /sbg/gps_pos
      - /sbg/gps_vel
      - /sbg/imu_data
      - /sbg/imu_short
      - /sbg/mag
      - /sbg/status
      - /sbg/utc_time
