# rosbag2 configuration for the all.launch.py bringup
# This configuration records all relevant topics for the vehicle
# Adjust the topics as necessary for your specific use case
# Removed topics with 0 message count: /imu/mag, /imu/nav_sat_fix, /imu/pres, /imu/utc_ref, /sbg/air_data, /sbg/gps_hdt, /sbg/gps_pos, /sbg/gps_raw, /sbg/gps_vel, /sbg/mag, /thruster_status_pwm
topics:
  - /navi_lidar/points
  - /camera_info
# - /image_raw
  - /image_raw/compressed
  - /imu/data
  - /imu/pos_ecef
  - /imu/temp
  - /imu/velocity
  - /sbg/ekf_euler
  - /sbg/ekf_nav
  - /sbg/ekf_quat
  - /sbg/imu_data
  - /sbg/status
  - /sbg/utc_time
  - /sbg/gps_raw
  - /thruster_command_pwm
  - /thruster_status_pwm
  - /speed_data
  - /battery_voltage
  - /temp_humidity
  - /ups_status
  - /water_quality
output: ros2_bringup_all_
