std_msgs/Header header
string run_id
int32 measurement_id
float64 elapsed_s

# C4E Conductivity sensor
float64 c4e_temp_c
float64 c4e_conductivity_uscm
float64 c4e_salinity_ppt
float64 c4e_tds_ppm

# OPTOD Oxygen sensor
float64 optod_temp_c
float64 optod_o2_saturation_pct
float64 optod_o2_mgl
float64 optod_o2_ppm

# pH/Redox sensor
float64 ph_temp_c
float64 ph_ph
float64 ph_redox_mv
float64 ph_mv
